// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
	[DbContext( typeof( AppDbContext ) )]
	partial class AppDbContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel( ModelBuilder modelBuilder )
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation( "ProductVersion", "9.0.5" )
				.HasAnnotation( "Relational:MaxIdentifierLength", 128 );

			SqlServerModelBuilderExtensions.UseIdentityColumns( modelBuilder );

			modelBuilder.Entity( "Domain.Employees.Employee", b =>
				{
					b.Property<Guid>( "Id" )
						.ValueGeneratedOnAdd()
						.HasColumnType( "uniqueidentifier" );

					b.Property<string>( "Name" )
						.IsRequired()
						.HasMaxLength( 100 )
						.HasColumnType( "nvarchar(100)" );

					b.Property<string>( "Position" )
						.IsRequired()
						.HasMaxLength( 50 )
						.HasColumnType( "nvarchar(50)" );

					b.Property<decimal>( "Salary" )
						.HasColumnType( "decimal(18,2)" );

					b.HasKey( "Id" );

					b.ToTable( "Employees" );
				} );
#pragma warning restore 612, 618
		}
	}
}
